// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package db

import (
	"context"
)

const clearAIAnnotations = `-- name: ClearAIAnnotations :exec
DELETE FROM annotations
WHERE annotations.layer = 'ai'
  AND EXISTS (SELECT 1 FROM assets WHERE assets.id = annotations.asset_id AND assets.owner_id = ?)
`

// Removes only ai-layer annotations for the owner's assets. Manual and
// extracted layers are never touched.
func (q *Queries) ClearAIAnnotations(ctx context.Context, ownerID string) error {
	_, err := q.db.ExecContext(ctx, clearAIAnnotations, ownerID)
	return err
}

const clearAIAssetTags = `-- name: ClearAIAssetTags :exec
DELETE FROM asset_tags
WHERE asset_tags.source = 'ai'
  AND EXISTS (SELECT 1 FROM assets WHERE assets.id = asset_tags.asset_id AND assets.owner_id = ?)
`

// Removes only AI-sourced tag links for the owner's assets. Manual links
// (source='manual') are left intact so the ai layer is separately clearable
// without touching user data (see docs/ai-and-3d.md).
func (q *Queries) ClearAIAssetTags(ctx context.Context, ownerID string) error {
	_, err := q.db.ExecContext(ctx, clearAIAssetTags, ownerID)
	return err
}

const getTagIDByName = `-- name: GetTagIDByName :one
SELECT id FROM tags WHERE owner_id = ? AND name = ?
`

type GetTagIDByNameParams struct {
	OwnerID string
	Name    string
}

// Resolves an owner's tag id by name so the AI pipeline can reuse an existing
// (possibly manual) tag instead of creating a duplicate. Returns sql.ErrNoRows
// when absent, signalling the caller to create it.
func (q *Queries) GetTagIDByName(ctx context.Context, arg GetTagIDByNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getTagIDByName, arg.OwnerID, arg.Name)
	var id string
	err := row.Scan(&id)
	return id, err
}
