// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotation.sql

package db

import (
	"context"
)

const upsertAnnotation = `-- name: UpsertAnnotation :exec
INSERT INTO annotations (asset_id, layer, "key", value, model, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(asset_id, layer, "key") DO UPDATE SET
    value      = excluded.value,
    model      = excluded.model,
    created_at = excluded.created_at
`

type UpsertAnnotationParams struct {
	AssetID   string
	Layer     string
	Key       string
	Value     string
	Model     string
	CreatedAt int64
}

func (q *Queries) UpsertAnnotation(ctx context.Context, arg UpsertAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnnotation,
		arg.AssetID,
		arg.Layer,
		arg.Key,
		arg.Value,
		arg.Model,
		arg.CreatedAt,
	)
	return err
}
