// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset_frame.sql

package db

import (
	"context"
)

const deleteAssetFramesByAsset = `-- name: DeleteAssetFramesByAsset :exec
DELETE FROM asset_frames WHERE asset_id = ?
`

func (q *Queries) DeleteAssetFramesByAsset(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssetFramesByAsset, assetID)
	return err
}

const insertAssetFrame = `-- name: InsertAssetFrame :exec
INSERT INTO asset_frames (asset_id, owner_id, frame_no, storage_path, name)
VALUES (?, ?, ?, ?, ?)
`

type InsertAssetFrameParams struct {
	AssetID     string
	OwnerID     string
	FrameNo     int64
	StoragePath string
	Name        string
}

func (q *Queries) InsertAssetFrame(ctx context.Context, arg InsertAssetFrameParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetFrame,
		arg.AssetID,
		arg.OwnerID,
		arg.FrameNo,
		arg.StoragePath,
		arg.Name,
	)
	return err
}

const listAssetFrames = `-- name: ListAssetFrames :many
SELECT asset_id, frame_no, storage_path, name
FROM asset_frames
WHERE asset_id = ? AND owner_id = ?
ORDER BY frame_no ASC
`

type ListAssetFramesParams struct {
	AssetID string
	OwnerID string
}

type ListAssetFramesRow struct {
	AssetID     string
	FrameNo     int64
	StoragePath string
	Name        string
}

func (q *Queries) ListAssetFrames(ctx context.Context, arg ListAssetFramesParams) ([]ListAssetFramesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetFrames, arg.AssetID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetFramesRow{}
	for rows.Next() {
		var i ListAssetFramesRow
		if err := rows.Scan(
			&i.AssetID,
			&i.FrameNo,
			&i.StoragePath,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
