// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset.sql

package db

import (
	"context"
	"database/sql"
)

const getAsset = `-- name: GetAsset :one
SELECT id, owner_id, kind, provider, storage_path, name, ext, size, hash,
       thumb_path, width, height, created_at, indexed_at,
       deleted_at, rating, color, display_name, folder_id, missing_at
FROM assets
WHERE id = ? AND owner_id = ?
`

type GetAssetParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAsset, arg.ID, arg.OwnerID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.Provider,
		&i.StoragePath,
		&i.Name,
		&i.Ext,
		&i.Size,
		&i.Hash,
		&i.ThumbPath,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.IndexedAt,
		&i.DeletedAt,
		&i.Rating,
		&i.Color,
		&i.DisplayName,
		&i.FolderID,
		&i.MissingAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, owner_id, kind, provider, storage_path, name, ext, size, hash,
       thumb_path, width, height, created_at, indexed_at,
       deleted_at, rating, color, display_name, folder_id, missing_at
FROM assets
WHERE owner_id = ? AND deleted_at IS NULL
ORDER BY indexed_at DESC
LIMIT ? OFFSET ?
`

type ListAssetsParams struct {
	OwnerID string
	Limit   int64
	Offset  int64
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssets, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Provider,
			&i.StoragePath,
			&i.Name,
			&i.Ext,
			&i.Size,
			&i.Hash,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.DeletedAt,
			&i.Rating,
			&i.Color,
			&i.DisplayName,
			&i.FolderID,
			&i.MissingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByHash = `-- name: ListAssetsByHash :many
SELECT id, owner_id, kind, provider, storage_path, name, ext, size, hash,
       thumb_path, width, height, created_at, indexed_at,
       deleted_at, rating, color, display_name, folder_id, missing_at
FROM assets
WHERE owner_id = ? AND hash = ? AND deleted_at IS NULL
ORDER BY indexed_at ASC
`

type ListAssetsByHashParams struct {
	OwnerID string
	Hash    string
}

// Returns all live assets with the given hash for the owner.
func (q *Queries) ListAssetsByHash(ctx context.Context, arg ListAssetsByHashParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByHash, arg.OwnerID, arg.Hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Provider,
			&i.StoragePath,
			&i.Name,
			&i.Ext,
			&i.Size,
			&i.Hash,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.DeletedAt,
			&i.Rating,
			&i.Color,
			&i.DisplayName,
			&i.FolderID,
			&i.MissingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuplicateHashes = `-- name: ListDuplicateHashes :many
SELECT hash, COUNT(*) AS cnt
FROM assets
WHERE owner_id = ? AND deleted_at IS NULL
GROUP BY hash
HAVING COUNT(*) > 1
ORDER BY cnt DESC
LIMIT ? OFFSET ?
`

type ListDuplicateHashesParams struct {
	OwnerID string
	Limit   int64
	Offset  int64
}

type ListDuplicateHashesRow struct {
	Hash string
	Cnt  int64
}

// Returns hashes that appear more than once among the owner's live assets.
func (q *Queries) ListDuplicateHashes(ctx context.Context, arg ListDuplicateHashesParams) ([]ListDuplicateHashesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDuplicateHashes, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateHashesRow{}
	for rows.Next() {
		var i ListDuplicateHashesRow
		if err := rows.Scan(&i.Hash, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveAssetsByProvider = `-- name: ListLiveAssetsByProvider :many
SELECT id, owner_id, kind, provider, storage_path, name, ext, size, hash,
       thumb_path, width, height, created_at, indexed_at,
       deleted_at, rating, color, display_name, folder_id, missing_at
FROM assets
WHERE owner_id = ? AND provider = ? AND deleted_at IS NULL AND missing_at IS NULL
ORDER BY storage_path ASC
`

type ListLiveAssetsByProviderParams struct {
	OwnerID  string
	Provider string
}

// Returns all live (non-trashed, non-missing) assets for a provider, used by
// the missing-file detector to check which indexed paths still exist on disk.
func (q *Queries) ListLiveAssetsByProvider(ctx context.Context, arg ListLiveAssetsByProviderParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listLiveAssetsByProvider, arg.OwnerID, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Provider,
			&i.StoragePath,
			&i.Name,
			&i.Ext,
			&i.Size,
			&i.Hash,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.DeletedAt,
			&i.Rating,
			&i.Color,
			&i.DisplayName,
			&i.FolderID,
			&i.MissingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissingAssets = `-- name: ListMissingAssets :many
SELECT id, owner_id, kind, provider, storage_path, name, ext, size, hash,
       thumb_path, width, height, created_at, indexed_at,
       deleted_at, rating, color, display_name, folder_id, missing_at
FROM assets
WHERE owner_id = ? AND missing_at IS NOT NULL AND deleted_at IS NULL
ORDER BY missing_at DESC
LIMIT ? OFFSET ?
`

type ListMissingAssetsParams struct {
	OwnerID string
	Limit   int64
	Offset  int64
}

func (q *Queries) ListMissingAssets(ctx context.Context, arg ListMissingAssetsParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listMissingAssets, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Provider,
			&i.StoragePath,
			&i.Name,
			&i.Ext,
			&i.Size,
			&i.Hash,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.DeletedAt,
			&i.Rating,
			&i.Color,
			&i.DisplayName,
			&i.FolderID,
			&i.MissingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissingAssetsByHash = `-- name: ListMissingAssetsByHash :many
SELECT id, owner_id, kind, provider, storage_path, name, ext, size, hash,
       thumb_path, width, height, created_at, indexed_at,
       deleted_at, rating, color, display_name, folder_id, missing_at
FROM assets
WHERE owner_id = ? AND hash = ? AND missing_at IS NOT NULL AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT 1
`

type ListMissingAssetsByHashParams struct {
	OwnerID string
	Hash    string
}

// Returns missing assets matching a given hash, oldest first (by created_at).
// Used by hash-based auto-reconnect during scan.
func (q *Queries) ListMissingAssetsByHash(ctx context.Context, arg ListMissingAssetsByHashParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listMissingAssetsByHash, arg.OwnerID, arg.Hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Provider,
			&i.StoragePath,
			&i.Name,
			&i.Ext,
			&i.Size,
			&i.Hash,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.DeletedAt,
			&i.Rating,
			&i.Color,
			&i.DisplayName,
			&i.FolderID,
			&i.MissingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebaseAssets = `-- name: RebaseAssets :exec
UPDATE assets
SET storage_path = ? || SUBSTR(storage_path, LENGTH(?) + 1),
    missing_at = NULL
WHERE owner_id = ? AND provider = ? AND storage_path LIKE ? || '%'
    AND deleted_at IS NULL
`

type RebaseAssetsParams struct {
	StoragePath string
	LENGTH      interface{}
	OwnerID     string
	Provider    string
	Column5     sql.NullString
}

// Batch-updates storage_path by replacing old_prefix with new_prefix for all
// assets whose path starts with old_prefix, and clears missing_at.
func (q *Queries) RebaseAssets(ctx context.Context, arg RebaseAssetsParams) error {
	_, err := q.db.ExecContext(ctx, rebaseAssets,
		arg.StoragePath,
		arg.LENGTH,
		arg.OwnerID,
		arg.Provider,
		arg.Column5,
	)
	return err
}

const relocateAsset = `-- name: RelocateAsset :exec
UPDATE assets
SET storage_path = ?, provider = ?, missing_at = NULL
WHERE id = ? AND owner_id = ?
`

type RelocateAssetParams struct {
	StoragePath string
	Provider    string
	ID          string
	OwnerID     string
}

// Updates the storage path (and optionally provider) of a single asset and
// clears missing_at. Used for manual relocate and hash-based auto-reconnect.
func (q *Queries) RelocateAsset(ctx context.Context, arg RelocateAssetParams) error {
	_, err := q.db.ExecContext(ctx, relocateAsset,
		arg.StoragePath,
		arg.Provider,
		arg.ID,
		arg.OwnerID,
	)
	return err
}

const upsertAsset = `-- name: UpsertAsset :exec
INSERT INTO assets (
    id, owner_id, kind, provider, storage_path, name, ext, size, hash,
    thumb_path, width, height, created_at, indexed_at,
    deleted_at, rating, color, display_name, folder_id, missing_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(owner_id, provider, storage_path) DO UPDATE SET
    kind       = excluded.kind,
    name       = excluded.name,
    ext        = excluded.ext,
    size       = excluded.size,
    hash       = excluded.hash,
    thumb_path = excluded.thumb_path,
    width      = excluded.width,
    height     = excluded.height,
    indexed_at = excluded.indexed_at
`

type UpsertAssetParams struct {
	ID          string
	OwnerID     string
	Kind        string
	Provider    string
	StoragePath string
	Name        string
	Ext         string
	Size        int64
	Hash        string
	ThumbPath   string
	Width       int64
	Height      int64
	CreatedAt   int64
	IndexedAt   int64
	DeletedAt   sql.NullInt64
	Rating      int64
	Color       string
	DisplayName string
	FolderID    string
	MissingAt   sql.NullInt64
}

// Re-indexing preserves user metadata: the ON CONFLICT clause updates only
// index-derived fields, leaving rating/color/display_name/folder_id/deleted_at
// (and thus trash state) and missing_at untouched.
func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) error {
	_, err := q.db.ExecContext(ctx, upsertAsset,
		arg.ID,
		arg.OwnerID,
		arg.Kind,
		arg.Provider,
		arg.StoragePath,
		arg.Name,
		arg.Ext,
		arg.Size,
		arg.Hash,
		arg.ThumbPath,
		arg.Width,
		arg.Height,
		arg.CreatedAt,
		arg.IndexedAt,
		arg.DeletedAt,
		arg.Rating,
		arg.Color,
		arg.DisplayName,
		arg.FolderID,
		arg.MissingAt,
	)
	return err
}
