// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset.sql

package db

import (
	"context"
	"database/sql"
)

const getAsset = `-- name: GetAsset :one
SELECT id, owner_id, kind, provider, storage_path, name, ext, size, hash,
       thumb_path, width, height, created_at, indexed_at,
       deleted_at, rating, color, display_name, folder_id
FROM assets
WHERE id = ? AND owner_id = ?
`

type GetAssetParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAsset, arg.ID, arg.OwnerID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.Provider,
		&i.StoragePath,
		&i.Name,
		&i.Ext,
		&i.Size,
		&i.Hash,
		&i.ThumbPath,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.IndexedAt,
		&i.DeletedAt,
		&i.Rating,
		&i.Color,
		&i.DisplayName,
		&i.FolderID,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, owner_id, kind, provider, storage_path, name, ext, size, hash,
       thumb_path, width, height, created_at, indexed_at,
       deleted_at, rating, color, display_name, folder_id
FROM assets
WHERE owner_id = ? AND deleted_at IS NULL
ORDER BY indexed_at DESC
LIMIT ? OFFSET ?
`

type ListAssetsParams struct {
	OwnerID string
	Limit   int64
	Offset  int64
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssets, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Provider,
			&i.StoragePath,
			&i.Name,
			&i.Ext,
			&i.Size,
			&i.Hash,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.DeletedAt,
			&i.Rating,
			&i.Color,
			&i.DisplayName,
			&i.FolderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAsset = `-- name: UpsertAsset :exec
INSERT INTO assets (
    id, owner_id, kind, provider, storage_path, name, ext, size, hash,
    thumb_path, width, height, created_at, indexed_at,
    deleted_at, rating, color, display_name, folder_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(owner_id, provider, storage_path) DO UPDATE SET
    kind       = excluded.kind,
    name       = excluded.name,
    ext        = excluded.ext,
    size       = excluded.size,
    hash       = excluded.hash,
    thumb_path = excluded.thumb_path,
    width      = excluded.width,
    height     = excluded.height,
    indexed_at = excluded.indexed_at
`

type UpsertAssetParams struct {
	ID          string
	OwnerID     string
	Kind        string
	Provider    string
	StoragePath string
	Name        string
	Ext         string
	Size        int64
	Hash        string
	ThumbPath   string
	Width       int64
	Height      int64
	CreatedAt   int64
	IndexedAt   int64
	DeletedAt   sql.NullInt64
	Rating      int64
	Color       string
	DisplayName string
	FolderID    string
}

// Re-indexing preserves user metadata: the ON CONFLICT clause updates only
// index-derived fields, leaving rating/color/display_name/folder_id/deleted_at
// (and thus trash state) untouched.
func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) error {
	_, err := q.db.ExecContext(ctx, upsertAsset,
		arg.ID,
		arg.OwnerID,
		arg.Kind,
		arg.Provider,
		arg.StoragePath,
		arg.Name,
		arg.Ext,
		arg.Size,
		arg.Hash,
		arg.ThumbPath,
		arg.Width,
		arg.Height,
		arg.CreatedAt,
		arg.IndexedAt,
		arg.DeletedAt,
		arg.Rating,
		arg.Color,
		arg.DisplayName,
		arg.FolderID,
	)
	return err
}
