// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const batchMoveToFolder = `-- name: BatchMoveToFolder :exec
UPDATE assets SET folder_id = ?
WHERE id IN (/*SLICE:ids*/?) AND owner_id = ? AND deleted_at IS NULL
`

type BatchMoveToFolderParams struct {
	FolderID string
	Ids      []string
	OwnerID  string
}

func (q *Queries) BatchMoveToFolder(ctx context.Context, arg BatchMoveToFolderParams) error {
	query := batchMoveToFolder
	var queryParams []interface{}
	queryParams = append(queryParams, arg.FolderID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const batchRestore = `-- name: BatchRestore :exec
UPDATE assets SET deleted_at = NULL
WHERE id IN (/*SLICE:ids*/?) AND owner_id = ? AND deleted_at IS NOT NULL
`

type BatchRestoreParams struct {
	Ids     []string
	OwnerID string
}

func (q *Queries) BatchRestore(ctx context.Context, arg BatchRestoreParams) error {
	query := batchRestore
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const batchTrash = `-- name: BatchTrash :exec
UPDATE assets SET deleted_at = ?
WHERE id IN (/*SLICE:ids*/?) AND owner_id = ? AND deleted_at IS NULL
`

type BatchTrashParams struct {
	DeletedAt sql.NullInt64
	Ids       []string
	OwnerID   string
}

func (q *Queries) BatchTrash(ctx context.Context, arg BatchTrashParams) error {
	query := batchTrash
	var queryParams []interface{}
	queryParams = append(queryParams, arg.DeletedAt)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const batchUpdateColor = `-- name: BatchUpdateColor :exec
UPDATE assets SET color = ?
WHERE id IN (/*SLICE:ids*/?) AND owner_id = ? AND deleted_at IS NULL
`

type BatchUpdateColorParams struct {
	Color   string
	Ids     []string
	OwnerID string
}

func (q *Queries) BatchUpdateColor(ctx context.Context, arg BatchUpdateColorParams) error {
	query := batchUpdateColor
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Color)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const batchUpdateDisplayName = `-- name: BatchUpdateDisplayName :exec
UPDATE assets SET display_name = ?
WHERE id IN (/*SLICE:ids*/?) AND owner_id = ? AND deleted_at IS NULL
`

type BatchUpdateDisplayNameParams struct {
	DisplayName string
	Ids         []string
	OwnerID     string
}

func (q *Queries) BatchUpdateDisplayName(ctx context.Context, arg BatchUpdateDisplayNameParams) error {
	query := batchUpdateDisplayName
	var queryParams []interface{}
	queryParams = append(queryParams, arg.DisplayName)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const batchUpdateRating = `-- name: BatchUpdateRating :exec
UPDATE assets SET rating = ?
WHERE id IN (/*SLICE:ids*/?) AND owner_id = ? AND deleted_at IS NULL
`

type BatchUpdateRatingParams struct {
	Rating  int64
	Ids     []string
	OwnerID string
}

func (q *Queries) BatchUpdateRating(ctx context.Context, arg BatchUpdateRatingParams) error {
	query := batchUpdateRating
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Rating)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const listTrashedAssets = `-- name: ListTrashedAssets :many
SELECT id, owner_id, kind, provider, storage_path, name, ext, size, hash,
       thumb_path, width, height, created_at, indexed_at,
       deleted_at, rating, color, display_name, folder_id, missing_at,
       current_version_id
FROM assets
WHERE owner_id = ? AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
LIMIT ? OFFSET ?
`

type ListTrashedAssetsParams struct {
	OwnerID string
	Limit   int64
	Offset  int64
}

func (q *Queries) ListTrashedAssets(ctx context.Context, arg ListTrashedAssetsParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listTrashedAssets, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Provider,
			&i.StoragePath,
			&i.Name,
			&i.Ext,
			&i.Size,
			&i.Hash,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.DeletedAt,
			&i.Rating,
			&i.Color,
			&i.DisplayName,
			&i.FolderID,
			&i.MissingAt,
			&i.CurrentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAssetsFound = `-- name: MarkAssetsFound :exec
UPDATE assets SET missing_at = NULL
WHERE id IN (/*SLICE:ids*/?) AND owner_id = ?
`

type MarkAssetsFoundParams struct {
	Ids     []string
	OwnerID string
}

func (q *Queries) MarkAssetsFound(ctx context.Context, arg MarkAssetsFoundParams) error {
	query := markAssetsFound
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const markAssetsMissing = `-- name: MarkAssetsMissing :exec
UPDATE assets SET missing_at = ?
WHERE id IN (/*SLICE:ids*/?) AND owner_id = ? AND deleted_at IS NULL
`

type MarkAssetsMissingParams struct {
	MissingAt sql.NullInt64
	Ids       []string
	OwnerID   string
}

func (q *Queries) MarkAssetsMissing(ctx context.Context, arg MarkAssetsMissingParams) error {
	query := markAssetsMissing
	var queryParams []interface{}
	queryParams = append(queryParams, arg.MissingAt)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const purgeTrash = `-- name: PurgeTrash :exec
DELETE FROM assets
WHERE owner_id = ? AND deleted_at IS NOT NULL AND deleted_at < ?
`

type PurgeTrashParams struct {
	OwnerID   string
	DeletedAt sql.NullInt64
}

func (q *Queries) PurgeTrash(ctx context.Context, arg PurgeTrashParams) error {
	_, err := q.db.ExecContext(ctx, purgeTrash, arg.OwnerID, arg.DeletedAt)
	return err
}

const setDisplayName = `-- name: SetDisplayName :exec
UPDATE assets SET display_name = ?
WHERE id = ? AND owner_id = ? AND deleted_at IS NULL
`

type SetDisplayNameParams struct {
	DisplayName string
	ID          string
	OwnerID     string
}

func (q *Queries) SetDisplayName(ctx context.Context, arg SetDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, setDisplayName, arg.DisplayName, arg.ID, arg.OwnerID)
	return err
}
