// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board.sql

package db

import (
	"context"
)

const createBoard = `-- name: CreateBoard :exec
INSERT INTO boards (id, owner_id, name, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateBoardParams struct {
	ID        string
	OwnerID   string
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) error {
	_, err := q.db.ExecContext(ctx, createBoard,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createBoardItem = `-- name: CreateBoardItem :one
INSERT INTO board_items (id, board_id, asset_id, x, y, w, h, rotation, z, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, board_id, asset_id, x, y, w, h, rotation, z, created_at
`

type CreateBoardItemParams struct {
	ID        string
	BoardID   string
	AssetID   string
	X         float64
	Y         float64
	W         float64
	H         float64
	Rotation  float64
	Z         int64
	CreatedAt int64
}

func (q *Queries) CreateBoardItem(ctx context.Context, arg CreateBoardItemParams) (BoardItem, error) {
	row := q.db.QueryRowContext(ctx, createBoardItem,
		arg.ID,
		arg.BoardID,
		arg.AssetID,
		arg.X,
		arg.Y,
		arg.W,
		arg.H,
		arg.Rotation,
		arg.Z,
		arg.CreatedAt,
	)
	var i BoardItem
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.AssetID,
		&i.X,
		&i.Y,
		&i.W,
		&i.H,
		&i.Rotation,
		&i.Z,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards WHERE id = ? AND owner_id = ?
`

type DeleteBoardParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) DeleteBoard(ctx context.Context, arg DeleteBoardParams) error {
	_, err := q.db.ExecContext(ctx, deleteBoard, arg.ID, arg.OwnerID)
	return err
}

const deleteBoardItem = `-- name: DeleteBoardItem :exec
DELETE FROM board_items WHERE id = ? AND board_id = ?
`

type DeleteBoardItemParams struct {
	ID      string
	BoardID string
}

func (q *Queries) DeleteBoardItem(ctx context.Context, arg DeleteBoardItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteBoardItem, arg.ID, arg.BoardID)
	return err
}

const deleteBoardItemsByBoard = `-- name: DeleteBoardItemsByBoard :exec
DELETE FROM board_items WHERE board_id = ?
`

func (q *Queries) DeleteBoardItemsByBoard(ctx context.Context, boardID string) error {
	_, err := q.db.ExecContext(ctx, deleteBoardItemsByBoard, boardID)
	return err
}

const getBoard = `-- name: GetBoard :one
SELECT id, owner_id, name, created_at, updated_at
FROM boards
WHERE id = ? AND owner_id = ?
`

type GetBoardParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) GetBoard(ctx context.Context, arg GetBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoard, arg.ID, arg.OwnerID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoardItems = `-- name: ListBoardItems :many
SELECT id, board_id, asset_id, x, y, w, h, rotation, z, created_at
FROM board_items
WHERE board_id = ?
ORDER BY z ASC, created_at ASC
`

func (q *Queries) ListBoardItems(ctx context.Context, boardID string) ([]BoardItem, error) {
	rows, err := q.db.QueryContext(ctx, listBoardItems, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardItem{}
	for rows.Next() {
		var i BoardItem
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.AssetID,
			&i.X,
			&i.Y,
			&i.W,
			&i.H,
			&i.Rotation,
			&i.Z,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoards = `-- name: ListBoards :many
SELECT id, owner_id, name, created_at, updated_at
FROM boards
WHERE owner_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListBoards(ctx context.Context, ownerID string) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, listBoards, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchBoard = `-- name: TouchBoard :exec
UPDATE boards SET updated_at = ? WHERE id = ?
`

type TouchBoardParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) TouchBoard(ctx context.Context, arg TouchBoardParams) error {
	_, err := q.db.ExecContext(ctx, touchBoard, arg.UpdatedAt, arg.ID)
	return err
}

const updateBoardName = `-- name: UpdateBoardName :exec
UPDATE boards SET name = ?, updated_at = ?
WHERE id = ? AND owner_id = ?
`

type UpdateBoardNameParams struct {
	Name      string
	UpdatedAt int64
	ID        string
	OwnerID   string
}

func (q *Queries) UpdateBoardName(ctx context.Context, arg UpdateBoardNameParams) error {
	_, err := q.db.ExecContext(ctx, updateBoardName,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	return err
}
