// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collection.sql

package db

import (
	"context"
)

const addCollectionItem = `-- name: AddCollectionItem :exec
INSERT INTO collection_items (collection_id, asset_id, ord)
VALUES (?, ?, ?)
ON CONFLICT(collection_id, asset_id) DO UPDATE SET ord = excluded.ord
`

type AddCollectionItemParams struct {
	CollectionID string
	AssetID      string
	Ord          int64
}

// Idempotent: re-adding an existing member updates its ord instead of failing.
func (q *Queries) AddCollectionItem(ctx context.Context, arg AddCollectionItemParams) error {
	_, err := q.db.ExecContext(ctx, addCollectionItem, arg.CollectionID, arg.AssetID, arg.Ord)
	return err
}

const clearCollectionCoverIfMatches = `-- name: ClearCollectionCoverIfMatches :exec
UPDATE collections SET cover = '' WHERE id = ? AND cover = ?
`

type ClearCollectionCoverIfMatchesParams struct {
	ID    string
	Cover string
}

// Clears an explicit cover override when the just-removed asset was it, so a
// removed member's thumbnail can never linger as the collection's cover (the
// effective-cover CASE in ListCollectionsWithCover has no membership check of
// its own; this keeps "cover is empty or a current member" true on the write
// side instead).
func (q *Queries) ClearCollectionCoverIfMatches(ctx context.Context, arg ClearCollectionCoverIfMatchesParams) error {
	_, err := q.db.ExecContext(ctx, clearCollectionCoverIfMatches, arg.ID, arg.Cover)
	return err
}

const createCollection = `-- name: CreateCollection :exec
INSERT INTO collections (id, owner_id, parent_id, name, cover)
VALUES (?, ?, ?, ?, ?)
`

type CreateCollectionParams struct {
	ID       string
	OwnerID  string
	ParentID string
	Name     string
	Cover    string
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, createCollection,
		arg.ID,
		arg.OwnerID,
		arg.ParentID,
		arg.Name,
		arg.Cover,
	)
	return err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = ? AND owner_id = ?
`

type DeleteCollectionParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, arg.ID, arg.OwnerID)
	return err
}

const deleteCollectionItemsByCollection = `-- name: DeleteCollectionItemsByCollection :exec
DELETE FROM collection_items WHERE collection_id = ?
`

func (q *Queries) DeleteCollectionItemsByCollection(ctx context.Context, collectionID string) error {
	_, err := q.db.ExecContext(ctx, deleteCollectionItemsByCollection, collectionID)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT id, owner_id, parent_id, name, cover
FROM collections
WHERE id = ? AND owner_id = ?
`

type GetCollectionParams struct {
	ID      string
	OwnerID string
}

// Returns the collection with its RAW stored cover (empty when auto-derived), so
// the edit path can distinguish an explicit override from the fallback. The
// resolved effective cover is a read-only concern of ListCollectionsWithCover.
func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, arg.ID, arg.OwnerID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Cover,
	)
	return i, err
}

const isCollectionMember = `-- name: IsCollectionMember :one
SELECT COUNT(*) AS n FROM collection_items WHERE collection_id = ? AND asset_id = ?
`

type IsCollectionMemberParams struct {
	CollectionID string
	AssetID      string
}

func (q *Queries) IsCollectionMember(ctx context.Context, arg IsCollectionMemberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isCollectionMember, arg.CollectionID, arg.AssetID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const listCollectionItemAssetIDs = `-- name: ListCollectionItemAssetIDs :many
SELECT asset_id FROM collection_items WHERE collection_id = ? ORDER BY ord ASC
`

func (q *Queries) ListCollectionItemAssetIDs(ctx context.Context, collectionID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionItemAssetIDs, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var asset_id string
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionItemsEnriched = `-- name: ListCollectionItemsEnriched :many
SELECT ci.asset_id, ci.ord, a.kind, a.name, a.display_name, a.thumb_path
FROM collection_items ci
JOIN assets a ON a.id = ci.asset_id
WHERE ci.collection_id = ?
ORDER BY ci.ord ASC
`

type ListCollectionItemsEnrichedRow struct {
	AssetID     string
	Ord         int64
	Kind        string
	Name        string
	DisplayName string
	ThumbPath   string
}

// Ordered membership joined to assets so kind/name/thumb are resolved in one
// query (mirroring boards' enrichment, but as a JOIN instead of N+1 GetAsset).
func (q *Queries) ListCollectionItemsEnriched(ctx context.Context, collectionID string) ([]ListCollectionItemsEnrichedRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionItemsEnriched, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionItemsEnrichedRow{}
	for rows.Next() {
		var i ListCollectionItemsEnrichedRow
		if err := rows.Scan(
			&i.AssetID,
			&i.Ord,
			&i.Kind,
			&i.Name,
			&i.DisplayName,
			&i.ThumbPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsWithCover = `-- name: ListCollectionsWithCover :many
SELECT c.id, c.owner_id, c.parent_id, c.name,
    CAST(CASE
        WHEN c.cover != '' THEN c.cover
        ELSE COALESCE((SELECT ci.asset_id FROM collection_items ci WHERE ci.collection_id = c.id ORDER BY ci.ord ASC LIMIT 1), '')
    END AS TEXT) AS effective_cover
FROM collections c
WHERE c.owner_id = ?
ORDER BY c.name, c.id
`

type ListCollectionsWithCoverRow struct {
	ID             string
	OwnerID        string
	ParentID       string
	Name           string
	EffectiveCover string
}

// Resolves each collection's effective cover in one pass: the explicit cover
// override when set, otherwise the lowest-ord member's asset_id, otherwise ” for
// an empty collection. CAST(... AS TEXT) pins the CASE result to a Go string.
func (q *Queries) ListCollectionsWithCover(ctx context.Context, ownerID string) ([]ListCollectionsWithCoverRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionsWithCover, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsWithCoverRow{}
	for rows.Next() {
		var i ListCollectionsWithCoverRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.EffectiveCover,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextCollectionItemOrd = `-- name: NextCollectionItemOrd :one
SELECT CAST(COALESCE(MAX(ord), -1) + 1 AS INTEGER) AS next_ord
FROM collection_items WHERE collection_id = ?
`

// max(ord)+1 for the next appended member; 0 for an empty collection.
func (q *Queries) NextCollectionItemOrd(ctx context.Context, collectionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextCollectionItemOrd, collectionID)
	var next_ord int64
	err := row.Scan(&next_ord)
	return next_ord, err
}

const removeCollectionItem = `-- name: RemoveCollectionItem :exec
DELETE FROM collection_items WHERE collection_id = ? AND asset_id = ?
`

type RemoveCollectionItemParams struct {
	CollectionID string
	AssetID      string
}

func (q *Queries) RemoveCollectionItem(ctx context.Context, arg RemoveCollectionItemParams) error {
	_, err := q.db.ExecContext(ctx, removeCollectionItem, arg.CollectionID, arg.AssetID)
	return err
}

const setCollectionItemOrd = `-- name: SetCollectionItemOrd :exec
UPDATE collection_items SET ord = ? WHERE collection_id = ? AND asset_id = ?
`

type SetCollectionItemOrdParams struct {
	Ord          int64
	CollectionID string
	AssetID      string
}

func (q *Queries) SetCollectionItemOrd(ctx context.Context, arg SetCollectionItemOrdParams) error {
	_, err := q.db.ExecContext(ctx, setCollectionItemOrd, arg.Ord, arg.CollectionID, arg.AssetID)
	return err
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections SET name = ?, parent_id = ?, cover = ?
WHERE id = ? AND owner_id = ?
`

type UpdateCollectionParams struct {
	Name     string
	ParentID string
	Cover    string
	ID       string
	OwnerID  string
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, updateCollection,
		arg.Name,
		arg.ParentID,
		arg.Cover,
		arg.ID,
		arg.OwnerID,
	)
	return err
}
