// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: color.sql

package db

import (
	"context"
	"strings"
)

const assetIDByPath = `-- name: AssetIDByPath :one
SELECT id FROM assets
WHERE owner_id = ? AND provider = ? AND storage_path = ?
`

type AssetIDByPathParams struct {
	OwnerID     string
	Provider    string
	StoragePath string
}

func (q *Queries) AssetIDByPath(ctx context.Context, arg AssetIDByPathParams) (string, error) {
	row := q.db.QueryRowContext(ctx, assetIDByPath, arg.OwnerID, arg.Provider, arg.StoragePath)
	var id string
	err := row.Scan(&id)
	return id, err
}

const assetsByIDs = `-- name: AssetsByIDs :many
SELECT id, owner_id, kind, provider, storage_path, name, ext, size, hash,
       thumb_path, width, height, created_at, indexed_at,
       deleted_at, rating, color, favorite, display_name, folder_id, missing_at,
       current_version_id, palette_manual
FROM assets
WHERE owner_id = ? AND id IN (/*SLICE:ids*/?)
`

type AssetsByIDsParams struct {
	OwnerID string
	Ids     []string
}

// Color-search / visual-similar results. thumb/dims stay the anchor's (not the
// current version): the color and pHash indexes are built from the anchor at
// scan time, so these discovery surfaces are anchor-scoped by construction.
func (q *Queries) AssetsByIDs(ctx context.Context, arg AssetsByIDsParams) ([]Asset, error) {
	query := assetsByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Provider,
			&i.StoragePath,
			&i.Name,
			&i.Ext,
			&i.Size,
			&i.Hash,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.DeletedAt,
			&i.Rating,
			&i.Color,
			&i.Favorite,
			&i.DisplayName,
			&i.FolderID,
			&i.MissingAt,
			&i.CurrentVersionID,
			&i.PaletteManual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const colorCandidates = `-- name: ColorCandidates :many
SELECT asset_id, hex, l, a, b FROM asset_colors
WHERE owner_id = ?
`

type ColorCandidatesRow struct {
	AssetID string
	Hex     string
	L       float64
	A       float64
	B       float64
}

func (q *Queries) ColorCandidates(ctx context.Context, ownerID string) ([]ColorCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, colorCandidates, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ColorCandidatesRow{}
	for rows.Next() {
		var i ColorCandidatesRow
		if err := rows.Scan(
			&i.AssetID,
			&i.Hex,
			&i.L,
			&i.A,
			&i.B,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAssetColors = `-- name: DeleteAssetColors :exec
DELETE FROM asset_colors WHERE asset_id = ?
`

func (q *Queries) DeleteAssetColors(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssetColors, assetID)
	return err
}

const getAssetColors = `-- name: GetAssetColors :many
SELECT ord, hex, weight FROM asset_colors
WHERE asset_id = ? AND owner_id = ?
ORDER BY ord ASC
`

type GetAssetColorsParams struct {
	AssetID string
	OwnerID string
}

type GetAssetColorsRow struct {
	Ord    int64
	Hex    string
	Weight float64
}

func (q *Queries) GetAssetColors(ctx context.Context, arg GetAssetColorsParams) ([]GetAssetColorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssetColors, arg.AssetID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssetColorsRow{}
	for rows.Next() {
		var i GetAssetColorsRow
		if err := rows.Scan(&i.Ord, &i.Hex, &i.Weight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaletteManual = `-- name: GetPaletteManual :one
SELECT palette_manual FROM assets WHERE id = ? AND owner_id = ?
`

type GetPaletteManualParams struct {
	ID      string
	OwnerID string
}

// The asset's palette_manual flag (0 = auto, 1 = user-curated). writePaletteTx
// reads it to skip re-scan overwrites of a curated palette (issue #62).
func (q *Queries) GetPaletteManual(ctx context.Context, arg GetPaletteManualParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPaletteManual, arg.ID, arg.OwnerID)
	var palette_manual int64
	err := row.Scan(&palette_manual)
	return palette_manual, err
}

const insertAssetColor = `-- name: InsertAssetColor :exec
INSERT INTO asset_colors (asset_id, owner_id, ord, hex, l, a, b, weight)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAssetColorParams struct {
	AssetID string
	OwnerID string
	Ord     int64
	Hex     string
	L       float64
	A       float64
	B       float64
	Weight  float64
}

func (q *Queries) InsertAssetColor(ctx context.Context, arg InsertAssetColorParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetColor,
		arg.AssetID,
		arg.OwnerID,
		arg.Ord,
		arg.Hex,
		arg.L,
		arg.A,
		arg.B,
		arg.Weight,
	)
	return err
}

const listAssetColorsFull = `-- name: ListAssetColorsFull :many
SELECT ord, hex, l, a, b, weight FROM asset_colors
WHERE asset_id = ? AND owner_id = ?
ORDER BY ord ASC
`

type ListAssetColorsFullParams struct {
	AssetID string
	OwnerID string
}

type ListAssetColorsFullRow struct {
	Ord    int64
	Hex    string
	L      float64
	A      float64
	B      float64
	Weight float64
}

// Every swatch with its full Lab coordinates, ord-ascending. Used by the manual
// delete path to re-insert the survivors with contiguous ords (0..N-1) without
// recomputing Lab, and to locate the target ord before deleting.
func (q *Queries) ListAssetColorsFull(ctx context.Context, arg ListAssetColorsFullParams) ([]ListAssetColorsFullRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetColorsFull, arg.AssetID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetColorsFullRow{}
	for rows.Next() {
		var i ListAssetColorsFullRow
		if err := rows.Scan(
			&i.Ord,
			&i.Hex,
			&i.L,
			&i.A,
			&i.B,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaletteManual = `-- name: SetPaletteManual :exec
UPDATE assets SET palette_manual = ? WHERE id = ? AND owner_id = ?
`

type SetPaletteManualParams struct {
	PaletteManual int64
	ID            string
	OwnerID       string
}

// Flips an asset's palette_manual flag; set to 1 by every manual edit so a later
// scan/thumb re-extract leaves the curated asset_colors rows untouched.
func (q *Queries) SetPaletteManual(ctx context.Context, arg SetPaletteManualParams) error {
	_, err := q.db.ExecContext(ctx, setPaletteManual, arg.PaletteManual, arg.ID, arg.OwnerID)
	return err
}

const updateAssetColorAt = `-- name: UpdateAssetColorAt :execrows
UPDATE asset_colors SET hex = ?, l = ?, a = ?, b = ?
WHERE asset_id = ? AND owner_id = ? AND ord = ?
`

type UpdateAssetColorAtParams struct {
	Hex     string
	L       float64
	A       float64
	B       float64
	AssetID string
	OwnerID string
	Ord     int64
}

// Repoints one swatch (by ord) at a new color; l/a/b are recomputed by the
// caller. :execrows so a missing ord reports 0 rows -> the handler answers 404.
func (q *Queries) UpdateAssetColorAt(ctx context.Context, arg UpdateAssetColorAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetColorAt,
		arg.Hex,
		arg.L,
		arg.A,
		arg.B,
		arg.AssetID,
		arg.OwnerID,
		arg.Ord,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
