// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: color.sql

package db

import (
	"context"
	"strings"
)

const assetIDByPath = `-- name: AssetIDByPath :one
SELECT id FROM assets
WHERE owner_id = ? AND provider = ? AND storage_path = ?
`

type AssetIDByPathParams struct {
	OwnerID     string
	Provider    string
	StoragePath string
}

func (q *Queries) AssetIDByPath(ctx context.Context, arg AssetIDByPathParams) (string, error) {
	row := q.db.QueryRowContext(ctx, assetIDByPath, arg.OwnerID, arg.Provider, arg.StoragePath)
	var id string
	err := row.Scan(&id)
	return id, err
}

const assetsByIDs = `-- name: AssetsByIDs :many
SELECT id, owner_id, kind, provider, storage_path, name, ext, size, hash,
       thumb_path, width, height, created_at, indexed_at,
       deleted_at, rating, color, display_name, folder_id
FROM assets
WHERE owner_id = ? AND id IN (/*SLICE:ids*/?)
`

type AssetsByIDsParams struct {
	OwnerID string
	Ids     []string
}

func (q *Queries) AssetsByIDs(ctx context.Context, arg AssetsByIDsParams) ([]Asset, error) {
	query := assetsByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OwnerID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Provider,
			&i.StoragePath,
			&i.Name,
			&i.Ext,
			&i.Size,
			&i.Hash,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.DeletedAt,
			&i.Rating,
			&i.Color,
			&i.DisplayName,
			&i.FolderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const colorCandidates = `-- name: ColorCandidates :many
SELECT asset_id, hex, l, a, b FROM asset_colors
WHERE owner_id = ?
`

type ColorCandidatesRow struct {
	AssetID string
	Hex     string
	L       float64
	A       float64
	B       float64
}

func (q *Queries) ColorCandidates(ctx context.Context, ownerID string) ([]ColorCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, colorCandidates, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ColorCandidatesRow{}
	for rows.Next() {
		var i ColorCandidatesRow
		if err := rows.Scan(
			&i.AssetID,
			&i.Hex,
			&i.L,
			&i.A,
			&i.B,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAssetColors = `-- name: DeleteAssetColors :exec
DELETE FROM asset_colors WHERE asset_id = ?
`

func (q *Queries) DeleteAssetColors(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssetColors, assetID)
	return err
}

const insertAssetColor = `-- name: InsertAssetColor :exec
INSERT INTO asset_colors (asset_id, owner_id, ord, hex, l, a, b, weight)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAssetColorParams struct {
	AssetID string
	OwnerID string
	Ord     int64
	Hex     string
	L       float64
	A       float64
	B       float64
	Weight  float64
}

func (q *Queries) InsertAssetColor(ctx context.Context, arg InsertAssetColorParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetColor,
		arg.AssetID,
		arg.OwnerID,
		arg.Ord,
		arg.Hex,
		arg.L,
		arg.A,
		arg.B,
		arg.Weight,
	)
	return err
}
