// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_page.sql

package db

import (
	"context"
)

const deleteDocumentPagesByAsset = `-- name: DeleteDocumentPagesByAsset :exec
DELETE FROM document_pages WHERE asset_id = ?
`

func (q *Queries) DeleteDocumentPagesByAsset(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentPagesByAsset, assetID)
	return err
}

const insertDocumentPage = `-- name: InsertDocumentPage :exec
INSERT INTO document_pages (asset_id, owner_id, page_no, thumb_path, width, height)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertDocumentPageParams struct {
	AssetID   string
	OwnerID   string
	PageNo    int64
	ThumbPath string
	Width     int64
	Height    int64
}

func (q *Queries) InsertDocumentPage(ctx context.Context, arg InsertDocumentPageParams) error {
	_, err := q.db.ExecContext(ctx, insertDocumentPage,
		arg.AssetID,
		arg.OwnerID,
		arg.PageNo,
		arg.ThumbPath,
		arg.Width,
		arg.Height,
	)
	return err
}

const listDocumentPages = `-- name: ListDocumentPages :many
SELECT asset_id, page_no, thumb_path, width, height
FROM document_pages
WHERE asset_id = ? AND owner_id = ?
ORDER BY page_no ASC
`

type ListDocumentPagesParams struct {
	AssetID string
	OwnerID string
}

type ListDocumentPagesRow struct {
	AssetID   string
	PageNo    int64
	ThumbPath string
	Width     int64
	Height    int64
}

func (q *Queries) ListDocumentPages(ctx context.Context, arg ListDocumentPagesParams) ([]ListDocumentPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentPages, arg.AssetID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentPagesRow{}
	for rows.Next() {
		var i ListDocumentPagesRow
		if err := rows.Scan(
			&i.AssetID,
			&i.PageNo,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
