// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embedding.sql

package db

import (
	"context"
)

const getEmbedding = `-- name: GetEmbedding :one
SELECT asset_id, embedding, model, created_at FROM embeddings WHERE asset_id = ?
`

func (q *Queries) GetEmbedding(ctx context.Context, assetID string) (Embedding, error) {
	row := q.db.QueryRowContext(ctx, getEmbedding, assetID)
	var i Embedding
	err := row.Scan(
		&i.AssetID,
		&i.Embedding,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const listOwnerEmbeddings = `-- name: ListOwnerEmbeddings :many
SELECT e.asset_id, e.embedding
FROM embeddings e
JOIN assets a ON a.id = e.asset_id
WHERE a.owner_id = ? AND a.deleted_at IS NULL
`

type ListOwnerEmbeddingsRow struct {
	AssetID   string
	Embedding []byte
}

func (q *Queries) ListOwnerEmbeddings(ctx context.Context, ownerID string) ([]ListOwnerEmbeddingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerEmbeddings, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerEmbeddingsRow{}
	for rows.Next() {
		var i ListOwnerEmbeddingsRow
		if err := rows.Scan(&i.AssetID, &i.Embedding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO embeddings (asset_id, embedding, model, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (asset_id) DO UPDATE SET
    embedding  = excluded.embedding,
    model      = excluded.model,
    created_at = excluded.created_at
`

type UpsertEmbeddingParams struct {
	AssetID   string
	Embedding []byte
	Model     string
	CreatedAt int64
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmbedding,
		arg.AssetID,
		arg.Embedding,
		arg.Model,
		arg.CreatedAt,
	)
	return err
}
