// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folder.sql

package db

import (
	"context"
)

const createFolder = `-- name: CreateFolder :exec
INSERT INTO folders (id, owner_id, parent_id, name, path)
VALUES (?, ?, ?, ?, ?)
`

type CreateFolderParams struct {
	ID       string
	OwnerID  string
	ParentID string
	Name     string
	Path     string
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) error {
	_, err := q.db.ExecContext(ctx, createFolder,
		arg.ID,
		arg.OwnerID,
		arg.ParentID,
		arg.Name,
		arg.Path,
	)
	return err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = ? AND owner_id = ?
`

type DeleteFolderParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) error {
	_, err := q.db.ExecContext(ctx, deleteFolder, arg.ID, arg.OwnerID)
	return err
}

const listFolders = `-- name: ListFolders :many
SELECT id, owner_id, parent_id, name, path
FROM folders
WHERE owner_id = ?
ORDER BY path
`

func (q *Queries) ListFolders(ctx context.Context, ownerID string) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFolders, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
