// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job.sql

package db

import (
	"context"
)

const enqueueJob = `-- name: EnqueueJob :exec
INSERT INTO jobs (id, owner_id, type, status, payload, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type EnqueueJobParams struct {
	ID        string
	OwnerID   string
	Type      string
	Status    string
	Payload   string
	CreatedAt int64
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) error {
	_, err := q.db.ExecContext(ctx, enqueueJob,
		arg.ID,
		arg.OwnerID,
		arg.Type,
		arg.Status,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const listJobs = `-- name: ListJobs :many
SELECT id, owner_id, type, status, payload, created_at
FROM jobs
WHERE owner_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListJobsParams struct {
	OwnerID string
	Limit   int64
	Offset  int64
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Type,
			&i.Status,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobProgress = `-- name: UpdateJobProgress :exec
UPDATE jobs SET status = ?, payload = ? WHERE id = ? AND owner_id = ?
`

type UpdateJobProgressParams struct {
	Status  string
	Payload string
	ID      string
	OwnerID string
}

// Updates status and payload together so a long-running job (e.g. a migration
// import) can persist progress counts in the payload JSON without a schema
// change. See internal/importers batch progress.
func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateJobProgress,
		arg.Status,
		arg.Payload,
		arg.ID,
		arg.OwnerID,
	)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs SET status = ? WHERE id = ? AND owner_id = ?
`

type UpdateJobStatusParams struct {
	Status  string
	ID      string
	OwnerID string
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus, arg.Status, arg.ID, arg.OwnerID)
	return err
}
