// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package db

import (
	"context"
)

const updateAssetCreatedAt = `-- name: UpdateAssetCreatedAt :exec
UPDATE assets SET created_at = ?
WHERE owner_id = ? AND provider = ? AND storage_path = ?
`

type UpdateAssetCreatedAtParams struct {
	CreatedAt   int64
	OwnerID     string
	Provider    string
	StoragePath string
}

// Updates asset.created_at when embedded metadata (EXIF) provides a capture
// time that should take priority over the filesystem modification time.
// Uses the natural key (owner_id, provider, storage_path) so the canonical
// row is resolved even after a re-scan discarded a fresh id on upsert.
func (q *Queries) UpdateAssetCreatedAt(ctx context.Context, arg UpdateAssetCreatedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetCreatedAt,
		arg.CreatedAt,
		arg.OwnerID,
		arg.Provider,
		arg.StoragePath,
	)
	return err
}
