// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Annotation struct {
	AssetID   string
	Layer     string
	Key       string
	Value     string
	Model     string
	CreatedAt int64
}

type Asset struct {
	ID          string
	OwnerID     string
	Kind        string
	Provider    string
	StoragePath string
	Name        string
	Ext         string
	Size        int64
	Hash        string
	ThumbPath   string
	Width       int64
	Height      int64
	CreatedAt   int64
	IndexedAt   int64
	DeletedAt   sql.NullInt64
	Rating      int64
	Color       string
	DisplayName string
	FolderID    string
}

type AssetColor struct {
	AssetID string
	OwnerID string
	Ord     int64
	Hex     string
	L       float64
	A       float64
	B       float64
	Weight  float64
}

type AssetTag struct {
	AssetID string
	TagID   string
	Source  string
}

type AssetsFt struct {
	Name        string
	Tags        string
	Description string
}

type Board struct {
	ID        string
	OwnerID   string
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

type BoardItem struct {
	ID        string
	BoardID   string
	AssetID   string
	X         float64
	Y         float64
	W         float64
	H         float64
	Rotation  float64
	Z         int64
	CreatedAt int64
}

type Embedding struct {
	AssetID   string
	Embedding []byte
	Model     string
	CreatedAt int64
}

type Folder struct {
	ID       string
	OwnerID  string
	ParentID string
	Name     string
	Path     string
}

type Job struct {
	ID        string
	OwnerID   string
	Type      string
	Status    string
	Payload   string
	CreatedAt int64
}

type Share struct {
	ID           string
	OwnerID      string
	TargetType   string
	TargetID     string
	Token        string
	ExpiresAt    sql.NullInt64
	PasswordHash string
	Permission   string
	CreatedAt    int64
}

type Tag struct {
	ID       string
	OwnerID  string
	ParentID string
	Name     string
	Color    string
}

type User struct {
	ID        string
	CreatedAt int64
}
