// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Annotation struct {
	AssetID   string
	Layer     string
	Key       string
	Value     string
	Model     string
	CreatedAt int64
}

type Asset struct {
	ID          string
	OwnerID     string
	Kind        string
	Provider    string
	StoragePath string
	Name        string
	Ext         string
	Size        int64
	Hash        string
	ThumbPath   string
	Width       int64
	Height      int64
	CreatedAt   int64
	IndexedAt   int64
}

type AssetColor struct {
	AssetID string
	OwnerID string
	Ord     int64
	Hex     string
	L       float64
	A       float64
	B       float64
	Weight  float64
}

type User struct {
	ID        string
	CreatedAt int64
}
