// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owner.sql

package db

import (
	"context"
)

const ensureOwner = `-- name: EnsureOwner :exec
INSERT INTO users (id, created_at)
VALUES (?, ?)
ON CONFLICT(id) DO NOTHING
`

type EnsureOwnerParams struct {
	ID        string
	CreatedAt int64
}

func (q *Queries) EnsureOwner(ctx context.Context, arg EnsureOwnerParams) error {
	_, err := q.db.ExecContext(ctx, ensureOwner, arg.ID, arg.CreatedAt)
	return err
}
