// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	EnsureOwner(ctx context.Context, arg EnsureOwnerParams) error
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error)
	UpsertAsset(ctx context.Context, arg UpsertAssetParams) error
}

var _ Querier = (*Queries)(nil)
