// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddAssetTag(ctx context.Context, arg AddAssetTagParams) error
	AssetIDByPath(ctx context.Context, arg AssetIDByPathParams) (string, error)
	AssetsByIDs(ctx context.Context, arg AssetsByIDsParams) ([]Asset, error)
	BatchMoveToFolder(ctx context.Context, arg BatchMoveToFolderParams) error
	BatchRemoveTags(ctx context.Context, arg BatchRemoveTagsParams) error
	BatchRestore(ctx context.Context, arg BatchRestoreParams) error
	BatchTrash(ctx context.Context, arg BatchTrashParams) error
	BatchUpdateColor(ctx context.Context, arg BatchUpdateColorParams) error
	BatchUpdateDisplayName(ctx context.Context, arg BatchUpdateDisplayNameParams) error
	BatchUpdateRating(ctx context.Context, arg BatchUpdateRatingParams) error
	// Removes only ai-layer annotations for the owner's assets. Manual and
	// extracted layers are never touched.
	ClearAIAnnotations(ctx context.Context, ownerID string) error
	// Removes only AI-sourced tag links for the owner's assets. Manual links
	// (source='manual') are left intact so the ai layer is separately clearable
	// without touching user data (see docs/ai-and-3d.md).
	ClearAIAssetTags(ctx context.Context, ownerID string) error
	ColorCandidates(ctx context.Context, ownerID string) ([]ColorCandidatesRow, error)
	CreateBoard(ctx context.Context, arg CreateBoardParams) error
	CreateBoardItem(ctx context.Context, arg CreateBoardItemParams) (BoardItem, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) error
	CreateShare(ctx context.Context, arg CreateShareParams) error
	CreateTag(ctx context.Context, arg CreateTagParams) error
	DeleteAssetColors(ctx context.Context, assetID string) error
	DeleteBoard(ctx context.Context, arg DeleteBoardParams) error
	DeleteBoardItem(ctx context.Context, arg DeleteBoardItemParams) error
	DeleteBoardItemsByBoard(ctx context.Context, boardID string) error
	DeleteFolder(ctx context.Context, arg DeleteFolderParams) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) error
	EnsureOwner(ctx context.Context, arg EnsureOwnerParams) error
	GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error)
	GetBoard(ctx context.Context, arg GetBoardParams) (Board, error)
	GetEmbedding(ctx context.Context, assetID string) (Embedding, error)
	GetShareByToken(ctx context.Context, token string) (Share, error)
	// Resolves an owner's tag id by name so the AI pipeline can reuse an existing
	// (possibly manual) tag instead of creating a duplicate. Returns sql.ErrNoRows
	// when absent, signalling the caller to create it.
	GetTagIDByName(ctx context.Context, arg GetTagIDByNameParams) (string, error)
	InsertAssetColor(ctx context.Context, arg InsertAssetColorParams) error
	ListAssetTags(ctx context.Context, assetID string) ([]Tag, error)
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error)
	// Returns all live assets with the given hash for the owner.
	ListAssetsByHash(ctx context.Context, arg ListAssetsByHashParams) ([]Asset, error)
	ListBoardItems(ctx context.Context, boardID string) ([]BoardItem, error)
	ListBoards(ctx context.Context, ownerID string) ([]Board, error)
	// Returns hashes that appear more than once among the owner's live assets.
	ListDuplicateHashes(ctx context.Context, arg ListDuplicateHashesParams) ([]ListDuplicateHashesRow, error)
	ListFolders(ctx context.Context, ownerID string) ([]Folder, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	// Returns all live (non-trashed, non-missing) assets for a provider, used by
	// the missing-file detector to check which indexed paths still exist on disk.
	ListLiveAssetsByProvider(ctx context.Context, arg ListLiveAssetsByProviderParams) ([]Asset, error)
	ListMissingAssets(ctx context.Context, arg ListMissingAssetsParams) ([]Asset, error)
	// Returns missing assets matching a given hash, oldest first (by created_at).
	// Used by hash-based auto-reconnect during scan.
	ListMissingAssetsByHash(ctx context.Context, arg ListMissingAssetsByHashParams) ([]Asset, error)
	ListOwnerEmbeddings(ctx context.Context, ownerID string) ([]ListOwnerEmbeddingsRow, error)
	// Returns all pHash annotations for the owner's live assets, joining through
	// assets to filter by owner and exclude trashed items.
	ListPHashAnnotations(ctx context.Context, ownerID string) ([]ListPHashAnnotationsRow, error)
	ListTags(ctx context.Context, ownerID string) ([]Tag, error)
	ListTrashedAssets(ctx context.Context, arg ListTrashedAssetsParams) ([]Asset, error)
	MarkAssetsFound(ctx context.Context, arg MarkAssetsFoundParams) error
	MarkAssetsMissing(ctx context.Context, arg MarkAssetsMissingParams) error
	PurgeTrash(ctx context.Context, arg PurgeTrashParams) error
	// Batch-updates storage_path by replacing old_prefix with new_prefix for all
	// assets whose path starts with old_prefix, and clears missing_at.
	RebaseAssets(ctx context.Context, arg RebaseAssetsParams) error
	// Updates the storage path (and optionally provider) of a single asset and
	// clears missing_at. Used for manual relocate and hash-based auto-reconnect.
	RelocateAsset(ctx context.Context, arg RelocateAssetParams) error
	SetDisplayName(ctx context.Context, arg SetDisplayNameParams) error
	TouchBoard(ctx context.Context, arg TouchBoardParams) error
	// Updates asset.created_at when embedded metadata (EXIF) provides a capture
	// time that should take priority over the filesystem modification time.
	// Uses the natural key (owner_id, provider, storage_path) so the canonical
	// row is resolved even after a re-scan discarded a fresh id on upsert.
	UpdateAssetCreatedAt(ctx context.Context, arg UpdateAssetCreatedAtParams) error
	UpdateBoardName(ctx context.Context, arg UpdateBoardNameParams) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpsertAnnotation(ctx context.Context, arg UpsertAnnotationParams) error
	// Re-indexing preserves user metadata: the ON CONFLICT clause updates only
	// index-derived fields, leaving rating/color/display_name/folder_id/deleted_at
	// (and thus trash state) and missing_at untouched.
	UpsertAsset(ctx context.Context, arg UpsertAssetParams) error
	UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error
}

var _ Querier = (*Queries)(nil)
