// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share.sql

package db

import (
	"context"
	"database/sql"
)

const createShare = `-- name: CreateShare :exec
INSERT INTO shares (
    id, owner_id, target_type, target_id, token,
    expires_at, password_hash, permission, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateShareParams struct {
	ID           string
	OwnerID      string
	TargetType   string
	TargetID     string
	Token        string
	ExpiresAt    sql.NullInt64
	PasswordHash string
	Permission   string
	CreatedAt    int64
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) error {
	_, err := q.db.ExecContext(ctx, createShare,
		arg.ID,
		arg.OwnerID,
		arg.TargetType,
		arg.TargetID,
		arg.Token,
		arg.ExpiresAt,
		arg.PasswordHash,
		arg.Permission,
		arg.CreatedAt,
	)
	return err
}

const getShareByToken = `-- name: GetShareByToken :one
SELECT id, owner_id, target_type, target_id, token,
       expires_at, password_hash, permission, created_at
FROM shares
WHERE token = ?
`

func (q *Queries) GetShareByToken(ctx context.Context, token string) (Share, error) {
	row := q.db.QueryRowContext(ctx, getShareByToken, token)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TargetType,
		&i.TargetID,
		&i.Token,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}
