// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag.sql

package db

import (
	"context"
	"strings"
)

const addAssetTag = `-- name: AddAssetTag :exec
INSERT INTO asset_tags (asset_id, tag_id, source)
VALUES (?, ?, ?)
ON CONFLICT(asset_id, tag_id) DO NOTHING
`

type AddAssetTagParams struct {
	AssetID string
	TagID   string
	Source  string
}

func (q *Queries) AddAssetTag(ctx context.Context, arg AddAssetTagParams) error {
	_, err := q.db.ExecContext(ctx, addAssetTag, arg.AssetID, arg.TagID, arg.Source)
	return err
}

const batchRemoveTags = `-- name: BatchRemoveTags :exec
DELETE FROM asset_tags
WHERE asset_id IN (/*SLICE:asset_ids*/?) AND tag_id = ?
`

type BatchRemoveTagsParams struct {
	AssetIds []string
	TagID    string
}

func (q *Queries) BatchRemoveTags(ctx context.Context, arg BatchRemoveTagsParams) error {
	query := batchRemoveTags
	var queryParams []interface{}
	if len(arg.AssetIds) > 0 {
		for _, v := range arg.AssetIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", strings.Repeat(",?", len(arg.AssetIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.TagID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const createTag = `-- name: CreateTag :exec
INSERT INTO tags (id, owner_id, parent_id, name, color)
VALUES (?, ?, ?, ?, ?)
`

type CreateTagParams struct {
	ID       string
	OwnerID  string
	ParentID string
	Name     string
	Color    string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) error {
	_, err := q.db.ExecContext(ctx, createTag,
		arg.ID,
		arg.OwnerID,
		arg.ParentID,
		arg.Name,
		arg.Color,
	)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ? AND owner_id = ?
`

type DeleteTagParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTag, arg.ID, arg.OwnerID)
	return err
}

const listAssetTags = `-- name: ListAssetTags :many
SELECT tags.id, tags.owner_id, tags.parent_id, tags.name, tags.color
FROM tags
JOIN asset_tags ON tags.id = asset_tags.tag_id
WHERE asset_tags.asset_id = ?
ORDER BY tags.name
`

func (q *Queries) ListAssetTags(ctx context.Context, assetID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listAssetTags, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, owner_id, parent_id, name, color
FROM tags
WHERE owner_id = ?
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context, ownerID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
