// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag.sql

package db

import (
	"context"
	"strings"
)

const addAssetTag = `-- name: AddAssetTag :exec
INSERT INTO asset_tags (asset_id, tag_id, source)
VALUES (?, ?, ?)
ON CONFLICT(asset_id, tag_id) DO NOTHING
`

type AddAssetTagParams struct {
	AssetID string
	TagID   string
	Source  string
}

func (q *Queries) AddAssetTag(ctx context.Context, arg AddAssetTagParams) error {
	_, err := q.db.ExecContext(ctx, addAssetTag, arg.AssetID, arg.TagID, arg.Source)
	return err
}

const batchRemoveTags = `-- name: BatchRemoveTags :exec
DELETE FROM asset_tags
WHERE asset_id IN (/*SLICE:asset_ids*/?) AND tag_id = ?
`

type BatchRemoveTagsParams struct {
	AssetIds []string
	TagID    string
}

func (q *Queries) BatchRemoveTags(ctx context.Context, arg BatchRemoveTagsParams) error {
	query := batchRemoveTags
	var queryParams []interface{}
	if len(arg.AssetIds) > 0 {
		for _, v := range arg.AssetIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", strings.Repeat(",?", len(arg.AssetIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.TagID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const createTag = `-- name: CreateTag :exec
INSERT INTO tags (id, owner_id, parent_id, name, color)
VALUES (?, ?, ?, ?, ?)
`

type CreateTagParams struct {
	ID       string
	OwnerID  string
	ParentID string
	Name     string
	Color    string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) error {
	_, err := q.db.ExecContext(ctx, createTag,
		arg.ID,
		arg.OwnerID,
		arg.ParentID,
		arg.Name,
		arg.Color,
	)
	return err
}

const deleteAssetTagsByTag = `-- name: DeleteAssetTagsByTag :exec
DELETE FROM asset_tags WHERE tag_id = ?
`

func (q *Queries) DeleteAssetTagsByTag(ctx context.Context, tagID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssetTagsByTag, tagID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ? AND owner_id = ?
`

type DeleteTagParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTag, arg.ID, arg.OwnerID)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, owner_id, parent_id, name, color
FROM tags
WHERE id = ? AND owner_id = ?
`

type GetTagParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, arg.ID, arg.OwnerID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const listAssetTags = `-- name: ListAssetTags :many
SELECT tags.id, tags.owner_id, tags.parent_id, tags.name, tags.color
FROM tags
JOIN asset_tags ON tags.id = asset_tags.tag_id
WHERE asset_tags.asset_id = ?
ORDER BY tags.name
`

func (q *Queries) ListAssetTags(ctx context.Context, assetID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listAssetTags, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, owner_id, parent_id, name, color
FROM tags
WHERE owner_id = ?
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context, ownerID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reattachAssetTags = `-- name: ReattachAssetTags :exec
INSERT OR IGNORE INTO asset_tags (asset_id, tag_id, source)
SELECT src.asset_id, ?1, src.source
FROM asset_tags AS src
WHERE src.tag_id = ?2
`

type ReattachAssetTagsParams struct {
	IntoTagID string
	FromTagID string
}

// Re-hang every asset carrying from_tag_id onto into_tag_id (global tag merge).
// INSERT OR IGNORE relies on the asset_tags (asset_id, tag_id) primary key to
// dedup: an asset already carrying both tags keeps its single into_tag_id row
// instead of failing on the conflict. The leftover from_tag_id rows are removed
// separately by DeleteAssetTagsByTag.
func (q *Queries) ReattachAssetTags(ctx context.Context, arg ReattachAssetTagsParams) error {
	_, err := q.db.ExecContext(ctx, reattachAssetTags, arg.IntoTagID, arg.FromTagID)
	return err
}

const reattachAssetTagsForAssets = `-- name: ReattachAssetTagsForAssets :exec
INSERT OR IGNORE INTO asset_tags (asset_id, tag_id, source)
SELECT src.asset_id, ?1, src.source
FROM asset_tags AS src
WHERE src.tag_id = ?2 AND src.asset_id IN (/*SLICE:asset_ids*/?)
`

type ReattachAssetTagsForAssetsParams struct {
	IntoTagID string
	FromTagID string
	AssetIds  []string
}

// Subset variant of ReattachAssetTags for batch replace: re-hang from_tag_id
// onto into_tag_id only on the given assets. Same (asset_id, tag_id) primary-key
// dedup as the global merge. from_tag_id itself is never deleted here (assets
// outside the subset may still use it); the caller removes it only within the
// subset via BatchRemoveTags.
func (q *Queries) ReattachAssetTagsForAssets(ctx context.Context, arg ReattachAssetTagsForAssetsParams) error {
	query := reattachAssetTagsForAssets
	var queryParams []interface{}
	queryParams = append(queryParams, arg.IntoTagID)
	queryParams = append(queryParams, arg.FromTagID)
	if len(arg.AssetIds) > 0 {
		for _, v := range arg.AssetIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", strings.Repeat(",?", len(arg.AssetIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const reparentTagChildren = `-- name: ReparentTagChildren :exec
UPDATE tags SET parent_id = ?1
WHERE parent_id = ?2 AND owner_id = ?3
`

type ReparentTagChildrenParams struct {
	NewParentID string
	OldParentID string
	OwnerID     string
}

// Promote a tag's direct children up one level to its own parent. Used by
// MergeTags before the merged-away tag is deleted so no child is left with a
// parent_id pointing at a now-deleted tag (a dangling ref). Safe even when the
// merge target is itself a child of the merged-away tag: it is promoted like any
// other child instead of pointing at the deleted parent or at itself.
func (q *Queries) ReparentTagChildren(ctx context.Context, arg ReparentTagChildrenParams) error {
	_, err := q.db.ExecContext(ctx, reparentTagChildren, arg.NewParentID, arg.OldParentID, arg.OwnerID)
	return err
}
