// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: version.sql

package db

import (
	"context"
)

const countVersion = `-- name: CountVersion :one
SELECT COUNT(*) FROM asset_versions
WHERE id = ? AND asset_id = ? AND owner_id = ?
`

type CountVersionParams struct {
	ID      string
	AssetID string
	OwnerID string
}

// Existence probe for a version by identity. Used inside SetCurrentVersion's
// transaction so a concurrent delete cannot leave current_version_id dangling.
func (q *Queries) CountVersion(ctx context.Context, arg CountVersionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVersion, arg.ID, arg.AssetID, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVersion = `-- name: CreateVersion :exec
INSERT INTO asset_versions (
    id, asset_id, owner_id, version_no, provider, storage_path, hash, size,
    thumb_path, width, height, note, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVersionParams struct {
	ID          string
	AssetID     string
	OwnerID     string
	VersionNo   int64
	Provider    string
	StoragePath string
	Hash        string
	Size        int64
	ThumbPath   string
	Width       int64
	Height      int64
	Note        string
	CreatedAt   int64
}

func (q *Queries) CreateVersion(ctx context.Context, arg CreateVersionParams) error {
	_, err := q.db.ExecContext(ctx, createVersion,
		arg.ID,
		arg.AssetID,
		arg.OwnerID,
		arg.VersionNo,
		arg.Provider,
		arg.StoragePath,
		arg.Hash,
		arg.Size,
		arg.ThumbPath,
		arg.Width,
		arg.Height,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const deleteVersion = `-- name: DeleteVersion :exec
DELETE FROM asset_versions
WHERE id = ? AND asset_id = ? AND owner_id = ?
`

type DeleteVersionParams struct {
	ID      string
	AssetID string
	OwnerID string
}

func (q *Queries) DeleteVersion(ctx context.Context, arg DeleteVersionParams) error {
	_, err := q.db.ExecContext(ctx, deleteVersion, arg.ID, arg.AssetID, arg.OwnerID)
	return err
}

const getAssetCurrentVersion = `-- name: GetAssetCurrentVersion :one
SELECT current_version_id FROM assets
WHERE id = ? AND owner_id = ?
`

type GetAssetCurrentVersionParams struct {
	ID      string
	OwnerID string
}

// The asset's current-version pointer (” when the asset has no explicit
// versions yet; the anchor row itself is the implicit single version).
func (q *Queries) GetAssetCurrentVersion(ctx context.Context, arg GetAssetCurrentVersionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getAssetCurrentVersion, arg.ID, arg.OwnerID)
	var current_version_id string
	err := row.Scan(&current_version_id)
	return current_version_id, err
}

const getVersionByNo = `-- name: GetVersionByNo :one
SELECT id, asset_id, owner_id, version_no, provider, storage_path, hash, size,
       thumb_path, width, height, note, created_at
FROM asset_versions
WHERE asset_id = ? AND owner_id = ? AND version_no = ?
`

type GetVersionByNoParams struct {
	AssetID   string
	OwnerID   string
	VersionNo int64
}

// One version addressed by (asset, version number); enforces ownership and that
// the version belongs to the asset. Used by set-current and delete.
func (q *Queries) GetVersionByNo(ctx context.Context, arg GetVersionByNoParams) (AssetVersion, error) {
	row := q.db.QueryRowContext(ctx, getVersionByNo, arg.AssetID, arg.OwnerID, arg.VersionNo)
	var i AssetVersion
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.OwnerID,
		&i.VersionNo,
		&i.Provider,
		&i.StoragePath,
		&i.Hash,
		&i.Size,
		&i.ThumbPath,
		&i.Width,
		&i.Height,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listVersions = `-- name: ListVersions :many
SELECT id, asset_id, owner_id, version_no, provider, storage_path, hash, size,
       thumb_path, width, height, note, created_at
FROM asset_versions
WHERE asset_id = ? AND owner_id = ?
ORDER BY version_no DESC
`

type ListVersionsParams struct {
	AssetID string
	OwnerID string
}

// All versions of an asset, newest version first.
func (q *Queries) ListVersions(ctx context.Context, arg ListVersionsParams) ([]AssetVersion, error) {
	rows, err := q.db.QueryContext(ctx, listVersions, arg.AssetID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetVersion{}
	for rows.Next() {
		var i AssetVersion
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.OwnerID,
			&i.VersionNo,
			&i.Provider,
			&i.StoragePath,
			&i.Hash,
			&i.Size,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxVersionNo = `-- name: MaxVersionNo :one
SELECT CAST(COALESCE(MAX(version_no), 0) AS INTEGER) AS max_no
FROM asset_versions
WHERE asset_id = ?
`

// Highest allocated version number for an asset (0 when none). CAST forces an
// int64 return so version-number allocation is MaxVersionNo + 1.
func (q *Queries) MaxVersionNo(ctx context.Context, assetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxVersionNo, assetID)
	var max_no int64
	err := row.Scan(&max_no)
	return max_no, err
}

const setAssetCurrentVersion = `-- name: SetAssetCurrentVersion :exec
UPDATE assets SET current_version_id = ?
WHERE id = ? AND owner_id = ?
`

type SetAssetCurrentVersionParams struct {
	CurrentVersionID string
	ID               string
	OwnerID          string
}

func (q *Queries) SetAssetCurrentVersion(ctx context.Context, arg SetAssetCurrentVersionParams) error {
	_, err := q.db.ExecContext(ctx, setAssetCurrentVersion, arg.CurrentVersionID, arg.ID, arg.OwnerID)
	return err
}
